import io

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from sqlalchemy.orm import Session

from app.database import get_db
from app.models import MaintenanceBill, Flat, Tower, Society, Payment, User
from app.security import get_current_user, ensure_flat_access

router = APIRouter(prefix="/receipts", tags=["receipts"])


@router.get("/bill/{bill_id}")
def bill_receipt(
    bill_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    bill = db.query(MaintenanceBill).get(bill_id)
    if not bill:
        raise HTTPException(status_code=404, detail="Bill not found")
    ensure_flat_access(db, current_user, bill.flat_id)

    payments = db.query(Payment).filter(Payment.bill_id == bill_id).all()
    if not payments:
        raise HTTPException(status_code=400, detail="No payment recorded for this bill yet")

    flat = db.query(Flat).get(bill.flat_id)
    tower = db.query(Tower).get(flat.tower_id)
    society = db.query(Society).get(tower.society_id)
    total_paid = sum(p.amount for p in payments)

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    y = height - 30 * mm

    c.setFont("Helvetica-Bold", 18)
    c.drawString(25 * mm, y, society.name)
    y -= 8 * mm
    c.setFont("Helvetica", 11)
    c.drawString(25 * mm, y, "Maintenance payment receipt")
    y -= 12 * mm

    c.setFont("Helvetica", 11)
    lines = [
        ("Receipt for", f"Flat {flat.number}, {tower.name}"),
        ("Billing period", f"{bill.period_month}/{bill.period_year}"),
        ("Bill amount", f"Rs {bill.amount:.0f}"),
        ("Late fee", f"Rs {bill.late_fee:.0f}"),
        ("Total paid", f"Rs {total_paid:.0f}"),
        ("Status", bill.status.value),
        ("Payments", str(len(payments))),
    ]
    for label, value in lines:
        c.drawString(25 * mm, y, label)
        c.drawString(95 * mm, y, value)
        y -= 8 * mm

    y -= 6 * mm
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(25 * mm, y, "Generated by SocietyOS. This is a system-generated receipt.")
    c.showPage()
    c.save()
    buf.seek(0)

    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f'inline; filename="receipt_bill_{bill_id}.pdf"'},
    )
